// <auto-generated />
using System;
using FreightLink.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FreightLink.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810172608_FixPaymentWebhookEventAppendOnlyTrigger")]
    partial class FixPaymentWebhookEventAppendOnlyTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FreightLink.Api.Entities.Agency", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BusinessRegNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("YardAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("YardLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("YardLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.HasKey("AgencyId");

                    b.HasIndex("BusinessRegNo")
                        .IsUnique()
                        .HasDatabaseName("uq_agency_regno");

                    b.HasIndex("YardLat", "YardLng")
                        .HasDatabaseName("ix_agency_active_yard")
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("Agencies", t =>
                        {
                            t.HasCheckConstraint("ck_agency_yard_lat", "\"YardLat\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_agency_yard_lng", "\"YardLng\" BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgencyStaff", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId");

                    b.HasIndex("AgencyId");

                    b.ToTable("AgencyStaff");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgencyStatusHistory", b =>
                {
                    b.Property<Guid>("AgencyStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AgencyStatusHistoryId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("AgencyStatusHistories", t =>
                        {
                            t.HasCheckConstraint("ck_ash_transition", "\"FromStatus\" IS DISTINCT FROM \"ToStatus\"");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgentStep", b =>
                {
                    b.Property<Guid>("AgentStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepNo")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentStepId");

                    b.HasIndex("WorkflowRunId", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("uq_agentstep_order");

                    b.ToTable("AgentSteps", t =>
                        {
                            t.HasCheckConstraint("ck_agentstep_failure", "\"Status\" <> 'Failed' OR \"ErrorMessage\" IS NOT NULL");

                            t.HasCheckConstraint("ck_agentstep_stepno", "\"StepNo\" >= 1");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgentWorkflowRun", b =>
                {
                    b.Property<Guid>("WorkflowRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TriggeredByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("WorkflowRunId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_awr_awaiting")
                        .HasFilter("\"Status\" = 'AwaitingApproval'");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("LoadId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("uq_awr_load_attempt");

                    b.ToTable("AgentWorkflowRuns", t =>
                        {
                            t.HasCheckConstraint("ck_awr_attempt", "\"AttemptNo\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_awr_completed", "\"CompletedAt\" IS NULL OR \"CompletedAt\" >= \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("ApprovalDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("ApprovalDecisionId");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("WorkflowRunId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_single_approve")
                        .HasFilter("\"Decision\" = 'Approve'");

                    b.HasIndex("WorkflowRunId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("uq_ad_sequence");

                    b.ToTable("ApprovalDecisions", t =>
                        {
                            t.HasCheckConstraint("ck_ad_reason", "\"Decision\" = 'Approve' OR \"Reason\" IS NOT NULL");

                            t.HasCheckConstraint("ck_ad_sequence", "\"SequenceNo\" >= 1");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Assignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProposedEtaMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProposedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("RoutedDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("LoadId")
                        .IsUnique()
                        .HasDatabaseName("ux_assignment_live_per_load")
                        .HasFilter("\"Status\" IN ('Proposed','Accepted')");

                    b.HasIndex("WorkflowRunId");

                    b.HasIndex("LoadId", "AgencyId")
                        .IsUnique()
                        .HasDatabaseName("ux_assignment_load_agency");

                    b.ToTable("Assignments", t =>
                        {
                            t.HasCheckConstraint("ck_assignment_distance", "\"RoutedDistanceKm\" IS NULL OR \"RoutedDistanceKm\" > 0");

                            t.HasCheckConstraint("ck_assignment_eta", "\"ProposedEtaMinutes\" IS NULL OR \"ProposedEtaMinutes\" > 0");

                            t.HasCheckConstraint("ck_assignment_price", "\"ProposedPrice\" > 0");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AssignmentResponse", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RespondedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssignmentId");

                    b.HasIndex("RespondedByUserId");

                    b.ToTable("AssignmentResponses", t =>
                        {
                            t.HasCheckConstraint("ck_ar_decline_reason", "\"Response\" <> 'Declined' OR \"DeclineReason\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.ComplianceDoc", b =>
                {
                    b.Property<Guid>("ComplianceDocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ComplianceDocId");

                    b.HasIndex("AgencyId", "DocType")
                        .IsUnique()
                        .HasDatabaseName("ux_compliancedoc_live")
                        .HasFilter("\"Status\" IN ('Pending','Verified')");

                    b.ToTable("ComplianceDocs", t =>
                        {
                            t.HasCheckConstraint("ck_compliancedoc_dates", "\"ExpiresOn\" IS NULL OR \"ExpiresOn\" > \"IssuedOn\"");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Dispute", b =>
                {
                    b.Property<Guid>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RaisedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("DisputeId");

                    b.HasIndex("RaisedByUserId");

                    b.HasIndex("TripId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ux_dispute_open")
                        .HasFilter("\"Status\" IN ('Open','UnderReview')");

                    b.ToTable("Disputes", t =>
                        {
                            t.HasCheckConstraint("ck_dispute_description", "length(trim(\"Description\")) >= 10");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.DisputeResolution", b =>
                {
                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("DisputeId");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("DisputeResolutions");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("LicenceExpiry")
                        .HasColumnType("date");

                    b.Property<string>("LicenceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DriverId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("LicenceNo")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_invoice_number");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("Invoices", t =>
                        {
                            t.HasCheckConstraint("ck_invoice_amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("ck_invoice_currency", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_invoice_due", "\"DueDate\" IS NULL OR \"DueDate\" >= (\"IssuedAt\" AT TIME ZONE 'UTC')::date");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Load", b =>
                {
                    b.Property<Guid>("LoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CargoDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DropoffAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DropoffLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("DropoffLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PickupLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("PickupLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset>("PickupWindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PickupWindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShipperUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("LoadId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_load_posted")
                        .HasFilter("\"Status\" = 'Posted'");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("uq_load_reference");

                    b.HasIndex("ShipperUserId");

                    b.ToTable("Loads", t =>
                        {
                            t.HasCheckConstraint("ck_load_distinct_points", "\"PickupLat\" <> \"DropoffLat\" OR \"PickupLng\" <> \"DropoffLng\"");

                            t.HasCheckConstraint("ck_load_dropoff_lat", "\"DropoffLat\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_load_dropoff_lng", "\"DropoffLng\" BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_load_pickup_lat", "\"PickupLat\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_load_pickup_lng", "\"PickupLng\" BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_load_price", "\"EstimatedPrice\" IS NULL OR \"EstimatedPrice\" > 0");

                            t.HasCheckConstraint("ck_load_volume", "\"VolumeM3\" > 0");

                            t.HasCheckConstraint("ck_load_weight", "\"WeightKg\" > 0");

                            t.HasCheckConstraint("ck_load_window", "\"PickupWindowEnd\" > \"PickupWindowStart\"");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.LoadFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("FileId");

                    b.HasIndex("LoadId");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("uq_file_storagekey");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Files", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_size", "\"SizeBytes\" > 0 AND \"SizeBytes\" <= 10485760");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.LoadStatusHistory", b =>
                {
                    b.Property<Guid>("LoadStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoadStatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("LoadId");

                    b.ToTable("LoadStatusHistories", t =>
                        {
                            t.HasCheckConstraint("ck_lsh_cancel_reason", "\"ToStatus\" <> 'Cancelled' OR \"Reason\" IS NOT NULL");

                            t.HasCheckConstraint("ck_lsh_transition", "\"FromStatus\" IS DISTINCT FROM \"ToStatus\"");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.MatchCandidate", b =>
                {
                    b.Property<Guid>("MatchCandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EligibilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("Eligible")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchCandidateId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("WorkflowRunId", "AgencyId")
                        .IsUnique()
                        .HasDatabaseName("uq_mc_run_agency");

                    b.HasIndex("WorkflowRunId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ux_mc_run_rank")
                        .HasFilter("\"Eligible\" = true");

                    b.ToTable("MatchCandidates", t =>
                        {
                            t.HasCheckConstraint("ck_mc_reason", "\"Eligible\" = true OR \"RejectionReason\" IS NOT NULL");

                            t.HasCheckConstraint("ck_mc_score", "\"EligibilityScore\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NotificationId");

                    b.HasIndex("LoadId");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notification_unread")
                        .HasFilter("\"ReadAt\" IS NULL");

                    b.ToTable("Notifications", t =>
                        {
                            t.HasCheckConstraint("ck_notification_email_delivery", "\"Channel\" <> 'Email' OR \"DeliveryStatus\" IS NOT NULL");

                            t.HasCheckConstraint("ck_notification_failure", "\"DeliveryStatus\" <> 'Failed' OR \"ErrorMessage\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GatewayRef")
                        .HasColumnType("text");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentId");

                    b.HasIndex("GatewayRef")
                        .IsUnique()
                        .HasDatabaseName("uq_payment_gatewayref");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_success")
                        .HasFilter("\"Status\" = 'Success'");

                    b.HasIndex("InvoiceId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("uq_payment_attempt");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("ck_payment_attempt", "\"AttemptNo\" >= 1");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.PaymentWebhookEvent", b =>
                {
                    b.Property<Guid>("PaymentWebhookEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("GatewayRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawPayloadHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SignatureValid")
                        .HasColumnType("boolean");

                    b.HasKey("PaymentWebhookEventId");

                    b.HasIndex("RawPayloadHash")
                        .IsUnique()
                        .HasDatabaseName("uq_pwe_payloadhash");

                    b.ToTable("PaymentWebhookEvents", t =>
                        {
                            t.HasCheckConstraint("ck_pwe_error", "\"ProcessingStatus\" <> 'Error' OR \"ErrorMessage\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refreshtoken_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refreshtoken_user_active")
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.ToTable("RefreshTokens", t =>
                        {
                            t.HasCheckConstraint("ck_refreshtoken_expiry", "\"ExpiresAt\" > \"IssuedAt\"");

                            t.HasCheckConstraint("ck_refreshtoken_revoked", "\"RevokedAt\" IS NULL OR \"RevokedAt\" >= \"IssuedAt\"");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.ShipperProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessRegNo")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId");

                    b.HasIndex("BusinessRegNo")
                        .IsUnique()
                        .HasDatabaseName("uq_shipperprofile_regno");

                    b.ToTable("ShipperProfiles");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.ToolCall", b =>
                {
                    b.Property<Guid>("ToolCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgentStepId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("RequestJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ToolCallId");

                    b.HasIndex("AgentStepId", "ToolName", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("uq_toolcall_attempt");

                    b.ToTable("ToolCalls", t =>
                        {
                            t.HasCheckConstraint("ck_toolcall_allowlist", "\"ToolName\" IN ('get_route_and_eta')");

                            t.HasCheckConstraint("ck_toolcall_attempt", "\"AttemptNo\" >= 1");

                            t.HasCheckConstraint("ck_toolcall_failure", "\"Success\" = true OR \"ErrorMessage\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Trip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("TripId");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_driver_live")
                        .HasFilter("\"Status\" IN ('Assigned','PickedUp','InTransit')");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_vehicle_live")
                        .HasFilter("\"Status\" IN ('Assigned','PickedUp','InTransit')");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.TripEvent", b =>
                {
                    b.Property<Guid>("TripEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SnapshotLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("SnapshotLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("TripEventId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("TripId");

                    b.ToTable("TripEvents", t =>
                        {
                            t.HasCheckConstraint("ck_tripevent_lat", "\"SnapshotLat\" IS NULL OR \"SnapshotLat\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_tripevent_lng", "\"SnapshotLng\" IS NULL OR \"SnapshotLng\" BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_tripevent_transition", "\"FromStatus\" IS DISTINCT FROM \"ToStatus\"");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.TripEvidence", b =>
                {
                    b.Property<Guid>("TripEvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CapturedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CapturedLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("CapturedLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("TripEvidenceId");

                    b.HasIndex("CapturedByUserId");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("uq_tripevidence_storagekey");

                    b.HasIndex("TripId", "EvidenceType")
                        .IsUnique()
                        .HasDatabaseName("uq_tripevidence_type");

                    b.ToTable("TripEvidences");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneE164")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_user_email");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("ck_user_email_format", "\"Email\" ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'");

                            t.HasCheckConstraint("ck_user_phone_e164", "\"PhoneE164\" IS NULL OR \"PhoneE164\" ~ '^\\+[1-9][0-9]{1,14}$'");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.HasKey("VehicleId");

                    b.HasIndex("AgencyId", "RegistrationNo")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicle_agency_regno");

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_capacity", "\"CapacityKg\" > 0");

                            t.HasCheckConstraint("ck_vehicle_volume", "\"VolumeM3\" > 0");
                        });
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgencyStaff", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Agency", "Agency")
                        .WithMany("Staff")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.User", "User")
                        .WithOne("AgencyStaff")
                        .HasForeignKey("FreightLink.Api.Entities.AgencyStaff", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgencyStatusHistory", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Agency", "Agency")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgentStep", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgentWorkflowRun", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Load", "Load")
                        .WithMany("WorkflowRuns")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.User", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");

                    b.Navigation("TriggeredByUser");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Assignment", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Agency", "Agency")
                        .WithMany("Assignments")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.Load", "Load")
                        .WithMany("Assignments")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("Assignments")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Load");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AssignmentResponse", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Assignment", "Assignment")
                        .WithOne("Response")
                        .HasForeignKey("FreightLink.Api.Entities.AssignmentResponse", "AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.User", "RespondedByUser")
                        .WithMany()
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("RespondedByUser");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.ComplianceDoc", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Agency", "Agency")
                        .WithMany("ComplianceDocs")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Dispute", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.Trip", "Trip")
                        .WithMany("Disputes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RaisedByUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.DisputeResolution", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Dispute", "Dispute")
                        .WithOne("Resolution")
                        .HasForeignKey("FreightLink.Api.Entities.DisputeResolution", "DisputeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispute");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Driver", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Agency", "Agency")
                        .WithMany("Drivers")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.User", "User")
                        .WithOne("DriverProfile")
                        .HasForeignKey("FreightLink.Api.Entities.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Invoice", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Trip", "Trip")
                        .WithOne("Invoice")
                        .HasForeignKey("FreightLink.Api.Entities.Invoice", "TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Load", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.User", "ShipperUser")
                        .WithMany()
                        .HasForeignKey("ShipperUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShipperUser");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.LoadFile", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Load", "Load")
                        .WithMany("Files")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.LoadStatusHistory", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.Load", "Load")
                        .WithMany("StatusHistory")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.MatchCandidate", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Agency", "Agency")
                        .WithMany("MatchCandidates")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("MatchCandidates")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Notification", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Load", "Load")
                        .WithMany("Notifications")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Payment", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.ShipperProfile", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.User", "User")
                        .WithOne("ShipperProfile")
                        .HasForeignKey("FreightLink.Api.Entities.ShipperProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.ToolCall", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.AgentStep", "AgentStep")
                        .WithMany("ToolCalls")
                        .HasForeignKey("AgentStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentStep");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Trip", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Assignment", "Assignment")
                        .WithOne("Trip")
                        .HasForeignKey("FreightLink.Api.Entities.Trip", "AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.TripEvent", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.Trip", "Trip")
                        .WithMany("Events")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecordedByUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.TripEvidence", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.User", "CapturedByUser")
                        .WithMany()
                        .HasForeignKey("CapturedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightLink.Api.Entities.Trip", "Trip")
                        .WithMany("Evidence")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapturedByUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Vehicle", b =>
                {
                    b.HasOne("FreightLink.Api.Entities.Agency", "Agency")
                        .WithMany("Vehicles")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Agency", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ComplianceDocs");

                    b.Navigation("Drivers");

                    b.Navigation("MatchCandidates");

                    b.Navigation("Staff");

                    b.Navigation("StatusHistory");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgentStep", b =>
                {
                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.AgentWorkflowRun", b =>
                {
                    b.Navigation("ApprovalDecisions");

                    b.Navigation("Assignments");

                    b.Navigation("MatchCandidates");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Assignment", b =>
                {
                    b.Navigation("Response");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Dispute", b =>
                {
                    b.Navigation("Resolution");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Driver", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Load", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Files");

                    b.Navigation("Notifications");

                    b.Navigation("StatusHistory");

                    b.Navigation("WorkflowRuns");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Trip", b =>
                {
                    b.Navigation("Disputes");

                    b.Navigation("Events");

                    b.Navigation("Evidence");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.User", b =>
                {
                    b.Navigation("AgencyStaff");

                    b.Navigation("DriverProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ShipperProfile");
                });

            modelBuilder.Entity("FreightLink.Api.Entities.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
